require("conf.treesitter")
require("conf.lspkind")
require("conf.cmp")
require("conf.nvim-tree")
require("conf.telescope")
require("conf.lualine")
require("conf.wilder")
require("conf.go")
require("conf.navigator")
require("conf.guihua")
require("conf.dap")
require("conf.noice")
require("conf.murmur")
require("conf.project")
require("conf.zen-mode")
require("conf.undotree")
require("conf.toggleterm")
-- require "conf.tokyonight"
-- require "conf.themer"
