require("conf.treesitter")
require("conf.lspkind")
require("conf.cmp")
-- require("conf.blink")
require("conf.nvim-tree")
require("conf.telescope")
require("conf.lualine")
-- require("conf.wilder")
require("conf.go")
require("conf.guihua")
require("conf.dap")
require("conf.noice")
require("conf.murmur")
require("conf.project")
-- require("conf.zen-mode")
require("conf.true-zen")
require("conf.undotree")
require("conf.toggleterm")
require("conf.conform")
-- require("conf.themer")
require("conf.lspsaga")
-- require("conf.navigator")
-- require "conf.tokyonight"
-- require("conf.chatGPT")
require("conf.line-diagnostic")
require("conf.avante")
require("conf.render-markdown")
require("conf.catppuccin")
